# Generated by Django 5.2.6 on 2025-10-02 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_language_book_languaje'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='date_of_dead',
            new_name='date_of_death'
        )
    ]
