# Generated by Django 5.2.6 on 2025-10-02 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_date_of_dead_to_date_of_death'),
    ]

    operations = [
            migrations.RenameField(
            model_name='book',
            old_name='languaje',
            new_name='language'
        )
    ]
